version: '2'

services:

  mongodb:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    networks:
      - back_network
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

    networks:
          - back_network
    depends_on:
      - mongodb

  node1:
    build: Node/.
    networks:
      - back_network
    depends_on:
      - "mongodb"
    environment:
      PORT: 3000
      JWT_Secret: "the_secret_jwt_key"
      DB_IP: "172.23.0.2"
      DB_PORT: "27017"
      DB_NAME: "mso"
      NODE_NAME: "node1"
  node2:
    build: Node/.
    networks:
      - back_network
    depends_on:
      - "mongodb"
    environment:
      PORT: 3000
      JWT_Secret: "the_secret_jwt_key"
      DB_IP: "172.23.0.2"
      DB_PORT: "27017"
      DB_NAME: "mso"
      NODE_NAME: "node2"
  node3:
    build: Node/.
    networks:
      - back_network
    depends_on:
      - "mongodb"
    environment:
      PORT: 3000
      JWT_Secret: "the_secret_jwt_key"
      DB_IP: "172.23.0.2"
      DB_PORT: "27017"
      DB_NAME: "mso"
      NODE_NAME: "node3"

  loadbalancer:
    build: NginX/.
    networks:
      - back_network
    ports:
      - '9001:9001'
    depends_on:
      - node1

networks:
  back_network:
    driver: bridge

